CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(190) DEFAULT NULL,
    cpf VARCHAR(11) DEFAULT NULL,
    password_hash VARCHAR(255) NOT NULL,
    must_change_password TINYINT(1) NOT NULL DEFAULT 0,
    role ENUM('ADMINISTRADOR', 'BACKOFFICE', 'BACKOFFICE SUPERVISOR') NOT NULL,
    regional_view ENUM('FULL', 'I', 'II', 'PERSONALIZADO') NOT NULL DEFAULT 'FULL',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    current_session_id VARCHAR(128) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    UNIQUE KEY uq_users_cpf (cpf),
    KEY idx_users_role (role),
    KEY idx_users_regional_view (regional_view),
    KEY idx_users_last_seen_at (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS import_batches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    original_filename VARCHAR(255) NOT NULL,
    csv_filename VARCHAR(255) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    eligible_rows INT NOT NULL DEFAULT 0,
    imported_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    filtered_out_count INT NOT NULL DEFAULT 0,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_import_batches_created_at (created_at),
    KEY idx_import_batches_user (created_by_user_id),
    CONSTRAINT fk_import_batches_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS catalog_products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PRODUTO_NOME` VARCHAR(255) NOT NULL,
    `PRODUTO_VALOR_GERENCIAL` DECIMAL(10,2) DEFAULT NULL,
    `PRODUTO_PONTUACAO_COMERCIAL` DECIMAL(10,2) DEFAULT NULL,
    `FATOR` DECIMAL(10,2) DEFAULT NULL,
    `CATEGORIA` VARCHAR(50) DEFAULT NULL,
    `TIPO` VARCHAR(50) DEFAULT NULL,
    `VIVO_TOTAL` VARCHAR(50) DEFAULT NULL,
    `TIPO_DOC` VARCHAR(20) DEFAULT NULL,
    `SOLO` VARCHAR(50) DEFAULT NULL,
    `2P` VARCHAR(50) DEFAULT NULL,
    `3P` VARCHAR(50) DEFAULT NULL,
    `DUO` VARCHAR(50) DEFAULT NULL,
    `PERIODO` VARCHAR(20) DEFAULT NULL,
    `ativo` TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_catalog_products_name_doc_period (`PRODUTO_NOME`, `TIPO_DOC`, `PERIODO`),
    KEY idx_catalog_products_name (`PRODUTO_NOME`),
    KEY idx_catalog_products_tipo (`TIPO`),
    KEY idx_catalog_products_categoria (`CATEGORIA`),
    KEY idx_catalog_products_ativo (`ativo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS hierarchy_bases (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    REGIONAL ENUM('I', 'II') DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hierarchy_bases_name (name),
    KEY idx_hierarchy_bases_regional (REGIONAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS hierarchy_base_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    base_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hierarchy_base_groups_name (name),
    KEY idx_hierarchy_base_groups_base_id (base_id),
    CONSTRAINT fk_hierarchy_base_groups_base FOREIGN KEY (base_id) REFERENCES hierarchy_bases (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS user_base_group_scopes (
    user_id BIGINT UNSIGNED NOT NULL,
    base_group_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, base_group_id),
    KEY idx_user_base_group_scopes_base_group (base_group_id),
    CONSTRAINT fk_user_base_group_scopes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_base_group_scopes_base_group FOREIGN KEY (base_group_id) REFERENCES hierarchy_base_groups (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS hierarchy_headcount_edits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    period_headcount VARCHAR(6) NOT NULL,
    downloaded_by_user_id BIGINT UNSIGNED NOT NULL,
    downloaded_at DATETIME NOT NULL,
    uploaded_at DATETIME DEFAULT NULL,
    resolved_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    resolved_at DATETIME DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hierarchy_headcount_edits_active (is_active),
    KEY idx_hierarchy_headcount_edits_period (period_headcount),
    KEY idx_hierarchy_headcount_edits_downloaded_by (downloaded_by_user_id),
    CONSTRAINT fk_hierarchy_headcount_edits_downloaded_by FOREIGN KEY (downloaded_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_hierarchy_headcount_edits_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS seller_hierarchies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    seller_name VARCHAR(150) NOT NULL,
    seller_cpf VARCHAR(14) NOT NULL,
    PERIODO_HEADCOUNT VARCHAR(6) NOT NULL DEFAULT '202603',
    role ENUM('CONSULTOR', 'SUPERVISOR', 'COORDENADOR', 'GERENTE') NOT NULL DEFAULT 'CONSULTOR',
    supervisor_name VARCHAR(150) NOT NULL,
    SUPERVISOR_CPF VARCHAR(14) DEFAULT NULL,
    coordinator_name VARCHAR(150) NOT NULL,
    COORDENADOR_CPF VARCHAR(14) DEFAULT NULL,
    manager_name VARCHAR(150) NOT NULL,
    GERENTE_BASE_CPF VARCHAR(14) DEFAULT NULL,
    base_id BIGINT UNSIGNED NOT NULL,
    base_group_id BIGINT UNSIGNED NOT NULL,
    CONSULTOR_BASE_REGIONAL VARCHAR(150) DEFAULT NULL,
    CONSULTOR_SETOR_NOME VARCHAR(150) DEFAULT NULL,
    CONSULTOR_SETOR_TIPO VARCHAR(50) DEFAULT NULL,
    GERENTE_TERRITORIO_NOME VARCHAR(150) DEFAULT NULL,
    GERENTE_TERRITORIO_CPF VARCHAR(14) DEFAULT NULL,
    created_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    updated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_seller_hierarchies_seller_cpf_periodo (seller_cpf, PERIODO_HEADCOUNT),
    KEY idx_seller_hierarchies_seller_name (seller_name),
    KEY idx_seller_hierarchies_periodo_headcount (PERIODO_HEADCOUNT),
    KEY idx_seller_hierarchies_base_id (base_id),
    KEY idx_seller_hierarchies_base_group_id (base_group_id),
    CONSTRAINT fk_seller_hierarchies_base FOREIGN KEY (base_id) REFERENCES hierarchy_bases (id),
    CONSTRAINT fk_seller_hierarchies_base_group FOREIGN KEY (base_group_id) REFERENCES hierarchy_base_groups (id),
    CONSTRAINT fk_seller_hierarchies_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_seller_hierarchies_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE seller_hierarchies
    ADD COLUMN IF NOT EXISTS role ENUM('CONSULTOR', 'SUPERVISOR', 'COORDENADOR', 'GERENTE') NOT NULL DEFAULT 'CONSULTOR' AFTER seller_cpf;

CREATE TABLE IF NOT EXISTS sales_import_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    import_batch_id BIGINT UNSIGNED NOT NULL,
    sale_code VARCHAR(100) NOT NULL,
    pdv_adabas VARCHAR(100) DEFAULT NULL,
    sale_input_date DATE DEFAULT NULL,
    sale_input_time TIME DEFAULT NULL,
    customer_document_type VARCHAR(10) DEFAULT NULL,
    customer_document VARCHAR(20) DEFAULT NULL,
    customer_name VARCHAR(255) DEFAULT NULL,
    phone_mobile VARCHAR(20) DEFAULT NULL,
    phone_alt_1 VARCHAR(20) DEFAULT NULL,
    phone_alt_2 VARCHAR(20) DEFAULT NULL,
    customer_email VARCHAR(255) DEFAULT NULL,
    customer_city VARCHAR(150) DEFAULT NULL,
    customer_uf VARCHAR(2) DEFAULT NULL,
    customer_regional VARCHAR(150) DEFAULT NULL,
    customer_cep VARCHAR(15) DEFAULT NULL,
    service_type VARCHAR(150) DEFAULT NULL,
    service_name VARCHAR(150) DEFAULT NULL,
    plan_name VARCHAR(255) DEFAULT NULL,
    package_name VARCHAR(255) DEFAULT NULL,
    composition_name VARCHAR(255) DEFAULT NULL,
    additional_services VARCHAR(255) DEFAULT NULL,
    additional_points VARCHAR(255) DEFAULT NULL,
    seller_cpf VARCHAR(20) DEFAULT NULL,
    sale_regional VARCHAR(150) DEFAULT NULL,
    ddd VARCHAR(5) DEFAULT NULL,
    service_order_number VARCHAR(150) DEFAULT NULL,
    cabinet_code VARCHAR(150) DEFAULT NULL,
    sale_customer_type VARCHAR(100) DEFAULT NULL,
    sale_status VARCHAR(60) DEFAULT NULL,
    service_status VARCHAR(60) DEFAULT NULL,
    audit_status ENUM('PENDENTE INPUT', 'AUDITANDO', 'FINALIZADA') NOT NULL DEFAULT 'PENDENTE INPUT',
    claimed_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    claimed_at DATETIME DEFAULT NULL,
    finalized_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sales_import_queue_sale_code (sale_code),
    KEY idx_sales_import_queue_status (audit_status),
    KEY idx_sales_import_queue_claimed_by (claimed_by_user_id),
    KEY idx_sales_import_queue_batch (import_batch_id),
    KEY idx_sales_import_queue_customer_document (customer_document),
    CONSTRAINT fk_sales_import_queue_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches (id),
    CONSTRAINT fk_sales_import_queue_claimed_by FOREIGN KEY (claimed_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS sale_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sale_code VARCHAR(100) NOT NULL,
    import_queue_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    action_type ENUM('ACESSO', 'ALTERACAO', 'FINALIZACAO') NOT NULL,
    summary VARCHAR(255) NOT NULL,
    changed_fields_json LONGTEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_sale_logs_sale_code (sale_code),
    KEY idx_sale_logs_import_queue (import_queue_id),
    KEY idx_sale_logs_user (user_id),
    CONSTRAINT fk_sale_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS post_sales_update_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    original_filename VARCHAR(255) DEFAULT NULL,
    total_rows INT UNSIGNED NOT NULL DEFAULT 0,
    updated_rows INT UNSIGNED NOT NULL DEFAULT 0,
    skipped_rows INT UNSIGNED NOT NULL DEFAULT 0,
    not_found_rows INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('SUCESSO', 'FALHA') NOT NULL DEFAULT 'SUCESSO',
    message VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_post_sales_update_logs_user (user_id),
    CONSTRAINT fk_post_sales_update_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS sales_nexus (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    IMPORT_QUEUE_ID BIGINT UNSIGNED NOT NULL,
    USUARIO_FINALIZACAO_ID BIGINT UNSIGNED DEFAULT NULL,
    VENDA_ID VARCHAR(100) DEFAULT NULL,
    VENDA_ORDEM_DE_SERVICO VARCHAR(150) DEFAULT NULL,
    POSVENDA_STATUS VARCHAR(20) DEFAULT NULL,
    POSVENDA_DATA_INSTALACAO DATE DEFAULT NULL,
    POSVENDA_SUB_STATUS VARCHAR(30) DEFAULT NULL,
    VENDA_DATA_INPUT DATE DEFAULT NULL,
    VENDA_DATA_INPUT_MES INT DEFAULT NULL,
    VENDA_DATA_INSTALACAO_AUDITORIA DATE DEFAULT NULL,
    CLIENTE_DOCUMENTO VARCHAR(20) DEFAULT NULL,
    CLIENTE_NOME_RAZAO_SOCIAL VARCHAR(255) DEFAULT NULL,
    CLIENTE_TIPO_DOCUMENTO VARCHAR(6) DEFAULT NULL,
    CLIENTE_DATA_NASCIMENTO DATE DEFAULT NULL,
    CLIENTE_MAE_NOME_FANTASIA VARCHAR(255) DEFAULT NULL,
    CLIENTE_TELEFONE_CELULAR VARCHAR(20) DEFAULT NULL,
    AUDITOR_NOME VARCHAR(150) DEFAULT NULL,
    VENDA_INSTACIA VARCHAR(150) DEFAULT NULL,
    VENDA_PROTOCOLO VARCHAR(150) DEFAULT NULL,
    CLIENTE_CIDADE_UF VARCHAR(4) DEFAULT NULL,
    CLIENTE_CIDADE_NOME VARCHAR(255) DEFAULT NULL,
    CLIENTE_LOGRADOURO_NOME VARCHAR(255) DEFAULT NULL,
    CLIENTE_LOGRADOURO_NUMERO VARCHAR(30) DEFAULT NULL,
    CLIENTE_LOGRADOURO_COMPLEMENTO VARCHAR(255) DEFAULT NULL,
    CLIENTE_BAIRRO_NOME VARCHAR(150) DEFAULT NULL,
    CNLAT_TERRITORIO VARCHAR(120) DEFAULT NULL,
    VENDA_MODALIDADE VARCHAR(20) DEFAULT NULL,
    PRODUTO_NOME VARCHAR(255) DEFAULT NULL,
    PRODUTO_PONTUACAO_COMERCIAL DECIMAL(10,2) DEFAULT NULL,
    PRODUTO_TIPO VARCHAR(255) DEFAULT NULL,
    PRODUTO_CATEGORIA VARCHAR(255) DEFAULT NULL,
    PRODUTO_TECNOLOGIA VARCHAR(255) DEFAULT NULL,
    PRODUTO_NOME_TIPO VARCHAR(20) DEFAULT NULL,
    CONSULTOR_NOME VARCHAR(150) DEFAULT NULL,
    CONSULTOR_TIPO VARCHAR(50) DEFAULT NULL,
    CONSULTOR_CPF VARCHAR(14) DEFAULT NULL,
    CONSULTOR_BASE_NOME VARCHAR(150) DEFAULT NULL,
    CONSULTOR_BASE_GRUPO VARCHAR(150) DEFAULT NULL,
    CONSULTOR_SETOR_NOME VARCHAR(20) DEFAULT NULL,
    CONSULTOR_SETOR_TIPO VARCHAR(6) DEFAULT NULL,
    SUPERVISOR_NOME VARCHAR(150) DEFAULT NULL,
    COORDENADOR_NOME VARCHAR(150) DEFAULT NULL,
    GERENTE_BASE_NOME VARCHAR(150) DEFAULT NULL,
    GERENTE_TERRITORIO_NOME VARCHAR(150) DEFAULT NULL,
    DIRETOR_NOME VARCHAR(150) DEFAULT NULL,
    VENDA_TIPO_DE_VENDA VARCHAR(50) DEFAULT NULL,
    CONSULTOR_BASE_REGIONAL VARCHAR(150) DEFAULT NULL,
    PRODUTO_VALOR_GERENCIAL DECIMAL(10,2) DEFAULT NULL,
    SGV_ADABAS_FIXA VARCHAR(100) DEFAULT NULL,
    VENDA_PERIODO_INPUT VARCHAR(6) DEFAULT NULL,
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY idx_sales_nexus_venda_id (VENDA_ID),
    KEY idx_sales_nexus_import_queue (IMPORT_QUEUE_ID),
    KEY idx_sales_nexus_consultor_cpf (CONSULTOR_CPF),
    KEY idx_sales_nexus_data_input (VENDA_DATA_INPUT),
    KEY idx_sales_nexus_periodo_input (VENDA_PERIODO_INPUT),
    CONSTRAINT fk_sales_nexus_import_queue FOREIGN KEY (IMPORT_QUEUE_ID) REFERENCES sales_import_queue (id),
    CONSTRAINT fk_sales_nexus_final_user FOREIGN KEY (USUARIO_FINALIZACAO_ID) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO users (name, email, cpf, password_hash, must_change_password, role)
VALUES
    ('Administrador', 'admin@vigg.local', '52998224725', '$2y$10$8.rUy8kCwNhdjSldRzMOSu0PKAf0ovCN2wbUBtetclMP/LYIftbXu', 0, 'ADMINISTRADOR'),
    ('Backoffice', 'backoffice@vigg.local', '11144477735', '$2y$10$n3K/5HpKa3.DgesD1CbbweV2njrvuWXZEyt86hVreq3YXdaUYvfg.', 0, 'BACKOFFICE'),
    ('Supervisor', 'supervisor@vigg.local', '12345678909', '$2y$10$5pEY1IYmoaWF4DqYcuoG7uCK2l0v33KFNNZl6WjepqSIwoJ.KC/BC', 0, 'BACKOFFICE SUPERVISOR')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    cpf = VALUES(cpf),
    password_hash = VALUES(password_hash),
    must_change_password = VALUES(must_change_password),
    role = VALUES(role),
    is_active = 1;
